[windows]
win_target ansible_host=192.168.182.134

[windows:vars]
ansible_user=admin
ansible_password=<REDACTED_LAB_PASSWORD>
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
